In [9]:
import numpy

In [10]:
size = int(input()) # 사이즈를 입력받는다.

 4


In [11]:
A = numpy.random.random((size, size))
print(A)

[[0.30186356 0.38132771 0.69927142 0.80925284]
 [0.55359032 0.89944734 0.271927   0.02417919]
 [0.3207496  0.59262604 0.3929922  0.62027862]
 [0.82409611 0.48994403 0.82402699 0.37745075]]


In [12]:
original_height, original_width = A.shape[0], A.shape[1]
pooled_height, pooled_width = A.shape[0] // 2, A.shape[1] // 2

In [13]:
B = A[:original_height, :original_width].reshape(pooled_height, 2, pooled_width, 2).max(axis=(1,3)) 

In [14]:
print(B)

[[0.89944734 0.80925284]
 [0.82409611 0.82402699]]
