In [1]:
import numpy

In [2]:
def max_value_in_2_2_area(A, area_address):
    '''
    A array에서 area_address로 시작하는 2*2 area 에서의 최대 값을 리턴한다.
    
    format of A : 2d array
    format of area_address : (number, number) 
    area_address[0] is X position
    area_address[1] is Y position
    '''
    x = area_address[0]
    y = area_address[1]
    return max(A[y][x], A[y+1][x], A[y][x+1], A[y+1][x+1])

In [3]:
def max_pooling(A, size):
    '''
     A array 를 max pooling 한다. 
    '''
    xy_pairs = [(x, y) for y in range(size) for x in range(size) if x%2 == 0 and y%2 == 0]
    result = numpy.ndarray(shape=(size//2,size//2))
    for xy in xy_pairs:
        result[xy[1]//2][xy[0]//2] = max_value_in_2_2_area(A, xy)
    return result

In [4]:
size = int(input()) # 사이즈를 입력받는다.

 4


In [5]:
A = numpy.random.random((size, size))

In [6]:
result = max_pooling(A, size)

In [7]:
print(A)

[[0.33078125 0.63936165 0.76711583 0.74797025]
 [0.51239059 0.71990612 0.08331715 0.3988731 ]
 [0.73709248 0.11062834 0.82975353 0.53590238]
 [0.75333292 0.04496026 0.15716293 0.6007824 ]]


In [8]:
print(result)

[[0.71990612 0.76711583]
 [0.75333292 0.82975353]]
